---
- name: Install SQL server
  win_chocolatey:
    name: sql-server-2019
    version: "{{ sql_version }}"
    state: present
  when: "inventory_hostname in groups['windows'] and '{{ operating_system }}' == 'Windows'"

- name: provision SQL RDS instance
  rds:
    command: create
    region: "{{ aws_region }}"
    instance_name: new-database
    db_engine: "{{ db_engine }}"
    size: 50
    instance_type: db.r5.large
    license_model: license-included
    username: "{{ username }}"
    password: "{{ password }}"
    tags:
      Environment: testing
      Application: cms
  when: "inventory_hostname in groups['rds'] and '{{ operating_system }}' == 'AWS'"
